language: node_js

sudo: false

node_js:
  - "12"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

env:
  - MONGODB_VERSION="2.6.12"
  - MONGODB_VERSION="3.0.15"
  - MONGODB_VERSION="3.2.16"
  - MONGODB_VERSION="3.4.7"
  - MONGODB_VERSION="4.0.0"

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB_VERSION}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB_VERSION}/bin/mongod --dbpath /tmp/data &> /dev/null &
  - ${PWD}/mongodb-linux-x86_64-${MONGODB_VERSION}/bin/mongod --version
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done

script: "npm test"
